name: download, parse, analyze and publish pipeline

on:
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: install requirements
        shell: bash
        run: pip install -r requirements.txt
      - name: crawl data
        shell: bash
        run: python src/crawler.py
      - name: parse data
        shell: bash
        run: python src/parser.py
      - name: generate html
        shell: bash
        run: python src/generator.py
      - name: deploy html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./html
          allow_empty_commit: true
      # artifact upload fails due to bug in action
      # https://github.com/actions/upload-artifact/issues/35
      # - name: upload data
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: data
      #     path: data
